# Generated by Django 4.0.3 on 2022-03-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dateCreation'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
